name = "SDiagonalizability"
uuid = "12271bdf-7740-497a-b7ef-3fbfedd57958"
keywords = ["quantum computing", "graph theory", "linear algebra", "physics"]
license = "MIT"
authors = ["Luis M. B. Varona <lbvarona@mta.ca>", "Nathaniel Johnston <njohnston@mta.ca>"]
description = "TODO:"
maintainers = ["Luis M. B. Varona <lbvarona@mta.ca>"]
readme = "README.md"
repository = "https://github.com/GraphQuantum/SDiagonalizability.jl"
version = "0.1.0-dev"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MolecularGraph = "6c89ec66-9cd8-5372-9f91-fabc50dd27fd"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Combinatorics = "1.0.2"
DataStructures = ">=0.18.15, <1.0"
Graphs = "1.10"
LinearAlgebra = "1.9"
MolecularGraph = ">=0.15.0, <1.0"
PrecompileTools = "1.2"
julia = "1.9"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
lint = ["JuliaFormatter"]
test = ["Test"]
