name = "SDiagonalizability"
uuid = "addecc1e-711d-4b49-877e-3152f1574f63"
keywords = ["graph theory", "linear algebra", "dynamic programming", "quantum computing"]
license = "MIT"
authors = ["Luis M. B. Varona <lm.varona@outlook.com>", "Nathaniel Johnston <nathaniel.johnston@gmail.com>"]
description = "A dynamic algorithm to minimize the S-bandwidth of an undirected graph, written in Julia."
homepage = "https://graphquantum.github.io/SDiagonalizability.jl/"
maintainers = ["Luis M. B. Varona <lm.varona@outlook.com>"]
readme = "README.md"
repository = "https://github.com/GraphQuantum/SDiagonalizability.jl"
version = "0.1.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixBandwidth = "075aa41b-24fd-4573-b25f-92cae432c0f8"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Combinatorics = "1.0"
DataStructures = "0.18.15 - 0.19"
ElasticArrays = "1.2"
Graphs = "1.10"
LinearAlgebra = "1.10"
MatrixBandwidth = "0.1 - 0.2"
PrecompileTools = "1.2"
julia = "1.10"
